// packages/calculator-core/src/ui/flowchart/node/IOConnectionMarker.vue
<script setup lang="ts">
import { css, cx } from '@doubleaxe/daxfb-calculator-styles/css';
import { PhArrowFatLinesDown, PhArrowFatLinesUp, PhX } from '@phosphor-icons/vue';
import type { Component } from 'vue';
import { computed } from 'vue';

import { EdgeStatus } from '#core/game/model/index.js';
import { actionIconIndicatorStyle } from '#core/styles/ActionIconIndicator.js';
import { StatusIconColor } from '#core/styles/StatusIcons.js';

const { status } = defineProps<{
    status: EdgeStatus;
}>();

const config = computed(() => {
    switch (status) {
        case EdgeStatus.ConnectedDest:
            return {
                icon: PhX as Component,
                color: StatusIconColor({ color: EdgeStatus.ConnectedDest }),
            };
        case EdgeStatus.ConnectionDest:
            return {
                icon: PhArrowFatLinesDown as Component,
                color: StatusIconColor({ color: EdgeStatus.ConnectionDest }),
            };
        case EdgeStatus.ConnectionOrigin:
            return {
                icon: PhArrowFatLinesUp as Component,
                color: StatusIconColor({ color: EdgeStatus.ConnectionOrigin }),
            };
        default:
            return undefined;
    }
});
</script>

<template>
    <component :is="config.icon" v-if="config" :class="cx(css(actionIconIndicatorStyle), config.color)" weight="bold" />
</template>

// packages/calculator-core/src/ui/flowchart/node/IOConnectionMarker.tsx
import { css, cx } from '@doubleaxe/daxfb-calculator-styles/css';
import { ArrowFatLinesDownIcon, ArrowFatLinesUpIcon, type Icon, XIcon } from '@phosphor-icons/react';
import { observer } from 'mobx-react-lite';

import { EdgeStatus } from '#core/game/model/index.js';
import { actionIconIndicatorStyle } from '#core/styles/ActionIconIndicator.js';
import { StatusIconColor } from '#core/styles/StatusIcons.js';

type Props = {
    status: EdgeStatus;
};

const statusConfig: Partial<Record<EdgeStatus, { color: string; icon: Icon }>> = {
    [EdgeStatus.ConnectionOrigin]: {
        icon: ArrowFatLinesUpIcon,
        color: StatusIconColor({ color: EdgeStatus.ConnectionOrigin }),
    },
    [EdgeStatus.ConnectionDest]: {
        icon: ArrowFatLinesDownIcon,
        color: StatusIconColor({ color: EdgeStatus.ConnectionDest }),
    },
    [EdgeStatus.ConnectedDest]: {
        icon: XIcon,
        color: StatusIconColor({ color: EdgeStatus.ConnectedDest }),
    },
};

const ConnectionMarker = observer(({ status }: Props) => {
    if (status === EdgeStatus.None) {
        return null;
    }

    const config = statusConfig[status];
    const Icon = config?.icon;
    return config && Icon ? <Icon className={cx(css(actionIconIndicatorStyle), config.color)} weight='bold' /> : null;
});

export default ConnectionMarker;
