// packages/calculator-core/src/ui/main/DragAndDropInitializer.tsx
import { Feedback, PointerActivationConstraints, PointerSensor } from '@dnd-kit/dom';
import { RestrictToWindow } from '@dnd-kit/dom/modifiers';
import { DragDropProvider } from '@dnd-kit/react';

import type { BaseProps } from '#core/types/props.js';

export default function DragAndDropInitializer({ children }: BaseProps) {
    return (
        <DragDropProvider
            modifiers={[RestrictToWindow]}
            plugins={(defaults) => [...defaults, Feedback.configure({ dropAnimation: null })]}
            sensors={() => [
                PointerSensor.configure({
                    activationConstraints: [
                        new PointerActivationConstraints.Distance({ value: 8 }),
                        new PointerActivationConstraints.Delay({ value: 400, tolerance: Infinity }),
                    ],
                }),
            ]}
        >
            {children}
        </DragDropProvider>
    );
}

// packages/calculator-core/src/ui/main/DragAndDropInitializer.vue
<script setup lang="ts">
import { Feedback, PointerActivationConstraints, PointerSensor } from '@dnd-kit/dom';
import { RestrictToWindow } from '@dnd-kit/dom/modifiers';
import { DragDropProvider } from '@dnd-kit/vue';

const modifiers = [RestrictToWindow];
const sensors = [
    PointerSensor.configure({
        activationConstraints: [
            new PointerActivationConstraints.Distance({ value: 8 }),
            new PointerActivationConstraints.Delay({ value: 400, tolerance: Infinity }),
        ],
    }),
];
</script>

<template>
    <DragDropProvider
        :modifiers="modifiers"
        :plugins="(defaults) => [...defaults, Feedback.configure({ dropAnimation: null })]"
        :sensors="sensors"
    >
        <slot />
    </DragDropProvider>
</template>
