// packages/calculator-core/src/ui/toolbar/ToolBarBase.vue
<script setup lang="ts">
import { css } from '@doubleaxe/daxfb-calculator-styles/css';
import { hstack } from '@doubleaxe/daxfb-calculator-styles/patterns';
import { PhList, PhMoon, PhSun, PhX } from '@phosphor-icons/vue';
import type { Component } from 'vue';
import { computed } from 'vue';

import { useDarkModeStore } from '#core/stores/DarkModeStore.js';
import { useFactoryPaletteState } from '#core/stores/FactoryPaletteState.js';

import ActionButton from '../components/ActionButton.vue';

const factoryPaletteState = useFactoryPaletteState();
const isDark = useDarkModeStore();

const paletteIcon = computed<Component>(() => (factoryPaletteState.factoryPaletteOpened ? PhX : PhList) as Component);
const schemeIcon = computed<Component>(() => (isDark.value ? PhSun : PhMoon) as Component);
</script>

<template>
    <div :class="hstack({ alignItems: 'center', justify: 'space-between' })">
        <div :class="hstack()">
            <ActionButton
                :icon="paletteIcon"
                title="Toggle palette"
                @click="factoryPaletteState.toggleFactoryPalette()"
            />
        </div>
        <div :class="hstack()">
            <ActionButton
                :class="css({ color: isDark ? 'var(--p-yellow-300)' : 'var(--p-blue-600)' })"
                :icon="schemeIcon"
                title="Toggle color scheme"
                @click="isDark = !isDark"
            />
        </div>
    </div>
</template>

// packages/calculator-core/src/ui/toolbar/ToolBarBase.tsx
import { hstack } from '@doubleaxe/daxfb-calculator-styles/patterns';
import { useMantineColorScheme } from '@mantine/core';
import { ListIcon, MoonIcon, SunIcon, XIcon } from '@phosphor-icons/react';
import { observer } from 'mobx-react-lite';

import { useFactoryPaletteState } from '#core/stores/FactoryPaletteState.js';

import ActionButton from '../components/ActionButton';

const ToolBarBase = observer(() => {
    const factoryPaletteState = useFactoryPaletteState();
    const { colorScheme, toggleColorScheme } = useMantineColorScheme();

    return (
        <div className={hstack({ alignItems: 'center', justify: 'space-between' })}>
            <div className={hstack()}>
                <ActionButton
                    icon={factoryPaletteState.factoryPaletteOpened ? <XIcon /> : <ListIcon />}
                    onClick={() => factoryPaletteState.toggleFactoryPalette()}
                    title='Toggle palette'
                />
            </div>
            <div className={hstack()}>
                <ActionButton
                    color={colorScheme === 'dark' ? 'yellow.3' : 'blue.6'}
                    icon={colorScheme === 'dark' ? <SunIcon /> : <MoonIcon />}
                    onClick={() => toggleColorScheme()}
                    title='Toggle color scheme'
                />
            </div>
        </div>
    );
});

export default ToolBarBase;
