// packages/calculator-games/coi/src/GameContextLoader.tsx
import { GameContextProvider } from '#game-ui-coi/game/parser/index.js';
import PageInitializer from '#game-ui-coi/ui/PageInitializer.jsx';

export default function GameContextLoader() {
    return (
        <GameContextProvider>
            <PageInitializer />
        </GameContextProvider>
    );
}

// packages/calculator-games/coi/src/GameContextLoader.vue
<script setup lang="ts">
import { css } from '@doubleaxe/daxfb-calculator-styles/css';

import GameContextProvider from '#game-ui-coi/game/parser/GameContextProvider.vue';
import PageInitializer from '#game-ui-coi/ui/PageInitializer.vue';
</script>

<template>
    <Suspense>
        <GameContextProvider>
            <PageInitializer />
        </GameContextProvider>
        <template #fallback>
            <div :class="css({ width: '100%', height: '100%' })" />
        </template>
    </Suspense>
</template>
