// packages/calculator-games/coi/src/ui/AppWindow.vue
<script setup lang="ts">
import FactoryPalette from '@doubleaxe/daxfb-calculator-core/ui/factory-palette/FactoryPalette.vue';
import FactoryPaletteItemList from '@doubleaxe/daxfb-calculator-core/ui/factory-palette/FactoryPaletteItemList.vue';
import FilterFactoryItem from '@doubleaxe/daxfb-calculator-core/ui/factory-palette/FilterFactoryItem.vue';
import FlowChartFrame from '@doubleaxe/daxfb-calculator-core/ui/flowchart/FlowChartFrame.vue';
import AppWindowBase from '@doubleaxe/daxfb-calculator-core/ui/main/AppWindowBase.vue';
import ToolBarBase from '@doubleaxe/daxfb-calculator-core/ui/toolbar/ToolBarBase.vue';
</script>

<template>
    <AppWindowBase>
        <template #toolbar>
            <ToolBarBase />
        </template>
        <template #factoryPalette>
            <FactoryPalette>
                <template #filterPanel>
                    <FilterFactoryItem />
                </template>
                <template #itemList>
                    <FactoryPaletteItemList />
                </template>
            </FactoryPalette>
        </template>
        <template #flowChart>
            <FlowChartFrame />
        </template>
    </AppWindowBase>
</template>

// packages/calculator-games/coi/src/ui/AppWindow.tsx
import FactoryPalette from '@doubleaxe/daxfb-calculator-core/ui/factory-palette/FactoryPalette';
import FactoryPaletteItemList from '@doubleaxe/daxfb-calculator-core/ui/factory-palette/FactoryPaletteItemList';
import FilterFactoryItem from '@doubleaxe/daxfb-calculator-core/ui/factory-palette/FilterFactoryItem';
import FlowChartFrame from '@doubleaxe/daxfb-calculator-core/ui/flowchart/FlowChartFrame';
import AppWindowBase from '@doubleaxe/daxfb-calculator-core/ui/main/AppWindowBase';
import ToolBarBase from '@doubleaxe/daxfb-calculator-core/ui/toolbar/ToolBarBase';

export default function AppWindow() {
    return (
        <AppWindowBase>
            <AppWindowBase.ToolBar>
                <ToolBarBase />
            </AppWindowBase.ToolBar>
            <AppWindowBase.FactoryPalette>
                <FactoryPalette>
                    <FactoryPalette.FilterPanel>
                        <FilterFactoryItem />
                    </FactoryPalette.FilterPanel>
                    <FactoryPalette.ItemList>
                        <FactoryPaletteItemList />
                    </FactoryPalette.ItemList>
                </FactoryPalette>
            </AppWindowBase.FactoryPalette>
            <AppWindowBase.FlowChart>
                <FlowChartFrame />
            </AppWindowBase.FlowChart>
        </AppWindowBase>
    );
}
