// packages/calculator-core/src/ui/flowchart/FlowChartFrame.tsx
import './flow.css';

import { useDroppable } from '@dnd-kit/react';
import { css } from '@doubleaxe/daxfb-calculator-styles/css';
import { ReactFlowProvider } from '@xyflow/react';
import type { MouseEvent as ReactMouseEvent } from 'react';

import { useFlowChartModelBase } from '#core/game/model/index.js';
import { FlowChartDroppable } from '#core/types/flowchart/types.js';

import FlowChart from './FlowChart.jsx';

export default function FlowChartFrame() {
    const flowChartModel = useFlowChartModelBase();
    const droppable = useDroppable({ id: FlowChartDroppable });

    const setNodeRef = (element: HTMLDivElement | null) => {
        droppable.ref(element);
    };

    const onClick = (event: ReactMouseEvent) => {
        flowChartModel.events.emit('paneClickAnywhere', event.nativeEvent);
    };

    return (
        <div className={css({ width: '100%', height: '100%' })} onClick={onClick} ref={setNodeRef}>
            <ReactFlowProvider>
                <FlowChart />
            </ReactFlowProvider>
        </div>
    );
}

// packages/calculator-core/src/ui/flowchart/FlowChartFrame.vue
<script setup lang="ts">
import './flow.css';

import { useDroppable } from '@dnd-kit/vue';
import { css } from '@doubleaxe/daxfb-calculator-styles/css';
import { shallowRef } from 'vue';

import { useFlowChartModelBase } from '#core/game/model/index.js';
import { FlowChartDroppable } from '#core/types/flowchart/types.js';

import FlowChart from './FlowChart.vue';

const flowChartModel = useFlowChartModelBase();

const element = shallowRef<HTMLElement | null>(null);
const setElementRef = (el: HTMLElement | null) => {
    element.value = el;
};
useDroppable({ id: FlowChartDroppable, element });

const onClick = (event: MouseEvent) => {
    flowChartModel.events.emit('paneClickAnywhere', event);
};
</script>

<template>
    <div
        :ref="(el) => setElementRef(el as HTMLElement | null)"
        :class="css({ width: '100%', height: '100%' })"
        @click="onClick"
    >
        <FlowChart />
    </div>
</template>
