// packages/calculator-core/src/ui/flowchart/FlowChartDropIndicator.vue
<script setup lang="ts">
import { css } from '@doubleaxe/daxfb-calculator-styles/css';
import { computed } from 'vue';

import type { GameItemBase } from '#core/game/parser/index.js';

import GameIconDragging from '../components/GameIconDragging.vue';

const {
    x,
    y,
    visible = false,
    item = undefined,
} = defineProps<{
    item?: GameItemBase;
    visible?: boolean;
    x: number;
    y: number;
}>();

const positionStyle = computed(() => ({
    '--indicator-x': `${x}px`,
    '--indicator-y': `${y}px`,
}));
</script>

<template>
    <div
        v-if="visible"
        :class="
            css({
                position: 'absolute',
                top: '0px',
                left: '0px',
                pointerEvents: 'none',
                transform: 'translate(var(--indicator-x), var(--indicator-y))',
            })
        "
        :style="positionStyle"
    >
        <GameIconDragging :item="item" />
    </div>
</template>

// packages/calculator-core/src/ui/flowchart/FlowChartDropIndicator.tsx
import { css } from '@doubleaxe/daxfb-calculator-styles/css';

import type { GameItemBase } from '#core/game/parser/index.js';

import GameIconDragging from '../components/GameIconDragging.jsx';

export type FlowChartDropIndicatorProps = {
    item?: GameItemBase;
    visible?: boolean;
    x: number;
    y: number;
};

export function FlowChartDropIndicator({ x, y, visible, item }: FlowChartDropIndicatorProps) {
    if (!visible) return null;

    return (
        <div
            className={css({
                position: 'absolute',
                top: '0px',
                left: '0px',
                pointerEvents: 'none',
            })}
            style={{
                transform: `translate(${x}px, ${y}px)`,
            }}
        >
            <GameIconDragging item={item} />
        </div>
    );
}
