// packages/calculator-core/src/ui/factory-palette/FactoryPaletteItemList.vue
<script setup lang="ts">
import { DragOverlay, useDragDropMonitor } from '@dnd-kit/vue';
import { hstack } from '@daxfb/styles/patterns';
import Divider from 'primevue/divider';
import { ref } from 'vue';

import type { GameItemBase } from '#core/game/parser/index.js';
import { useGameDataBase } from '#core/game/parser/index.js';
import { useFactoryPaletteState } from '#core/stores/FactoryPaletteState.js';
import { useFilterStoreBase } from '#core/stores/FilterStoreBase.js';

import GameIconDragging from '../components/GameIconDragging.vue';
import GameIconDraggableSelectable from './GameIconDraggableSelectable.vue';

const gameData = useGameDataBase();
const filterStore = useFilterStoreBase();
const factoryPaletteState = useFactoryPaletteState();

const dragItem = ref<GameItemBase | undefined>(undefined);

useDragDropMonitor({
    onDragStart(event) {
        if (typeof event.operation.source?.id === 'string') {
            dragItem.value = gameData.getGameItem(event.operation.source.id);
            factoryPaletteState.setSelectedFactory(undefined);
        }
    },
    onDragEnd() {
        dragItem.value = undefined;
    },
});

const factoryFromEvent = (target: EventTarget | null) => {
    const itemFromEvent = (target as HTMLElement | null)?.closest('[data-item]');
    if (!itemFromEvent) return undefined;
    return gameData.getGameItem(itemFromEvent.getAttribute('data-item') ?? '');
};
const handleItemClick = (factory: GameItemBase | undefined) => {
    if (factory === undefined) {
        factoryPaletteState.setSelectedFactory(undefined);
        return;
    }
    factoryPaletteState.setSelectedFactory(factoryPaletteState.selectedFactory === factory ? undefined : factory);
};
const handleItemKeydown = (event: KeyboardEvent) => {
    if (event.key === 'Enter' || event.key === ' ') {
        event.preventDefault();
        handleItemClick(factoryFromEvent(event.target));
    }
};
</script>

<template>
    <div
        :class="hstack({ gap: '2px', padding: '2', flexWrap: 'wrap' })"
        @click="handleItemClick(factoryFromEvent($event.target))"
        @keydown="handleItemKeydown"
    >
        <template v-for="(group, index) in filterStore.filter" :key="index">
            <Divider v-if="index" />
            <GameIconDraggableSelectable
                v-for="item in group"
                :key="item.key"
                border-style="plain"
                :is-selected="factoryPaletteState.selectedFactory === item"
                :item="item"
            />
        </template>
    </div>
    <Teleport to="body">
        <DragOverlay :drop-animation="null">
            <GameIconDragging :item="dragItem" />
        </DragOverlay>
    </Teleport>
</template>

// packages/calculator-core/src/ui/factory-palette/FactoryPaletteItemList.tsx
import { DragOverlay, useDragDropMonitor } from '@dnd-kit/react';
import { hstack } from '@daxfb/styles/patterns';
import { Divider } from '@mantine/core';
import { action } from 'mobx';
import { observer } from 'mobx-react-lite';
import { useState } from 'react';
import { Fragment } from 'react/jsx-runtime';
import { createPortal } from 'react-dom';

import type { GameItemBase } from '#core/game/parser/index.js';
import { useGameDataBase } from '#core/game/parser/index.js';
import { useFactoryPaletteState } from '#core/stores/FactoryPaletteState.js';
import { useFilterStoreBase } from '#core/stores/FilterStoreBase.js';

import GameIconDragging from '../components/GameIconDragging.jsx';
import GameIconDraggableSelectable from './GameIconDraggableSelectable.jsx';

const FactoryPaletteItemList = observer(() => {
    const gameData = useGameDataBase();
    const filterStore = useFilterStoreBase();
    const factoryPaletteState = useFactoryPaletteState();

    const [dragItem, setDragItem] = useState<GameItemBase | undefined>(undefined);

    useDragDropMonitor({
        onDragStart(event) {
            if (typeof event.operation.source?.id === 'string') {
                setDragItem(gameData.getGameItem(event.operation.source?.id));
                factoryPaletteState.setSelectedFactory(undefined);
            }
        },
        onDragEnd() {
            setDragItem(undefined);
        },
    });

    const factoryFromEvent = (target: EventTarget) => {
        const itemFromEvent = (target as HTMLElement).closest('[data-item]');
        if (!itemFromEvent) return undefined;
        return gameData.getGameItem(itemFromEvent.getAttribute('data-item') ?? '');
    };
    const handleItemClick = action((factory: GameItemBase | undefined) => {
        if (factory === undefined) {
            factoryPaletteState.setSelectedFactory(undefined);
            return;
        }
        factoryPaletteState.setSelectedFactory(factoryPaletteState.selectedFactory === factory ? undefined : factory);
    });

    return (
        <>
            <div
                className={hstack({
                    gap: '2px',
                    padding: 'var(--mantine-spacing-xs)',
                    flexWrap: 'wrap',
                })}
                onClick={(e) => handleItemClick(factoryFromEvent(e.target))}
                onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                        e.preventDefault();
                        handleItemClick(factoryFromEvent(e.target));
                    }
                }}
            >
                {filterStore.filter.map((group, index) => (
                    <Fragment key={index}>
                        {index ? <Divider /> : undefined}
                        {group.map((item) => (
                            <GameIconDraggableSelectable
                                borderStyle={'plain'}
                                isSelected={factoryPaletteState.selectedFactory === item}
                                item={item}
                                key={item.key}
                            />
                        ))}
                    </Fragment>
                ))}
            </div>
            {createPortal(
                <DragOverlay dropAnimation={null}>
                    <GameIconDragging item={dragItem} />
                </DragOverlay>,
                document.body
            )}
        </>
    );
});

export default FactoryPaletteItemList;
