// packages/calculator-core/src/ui/factory-palette/FactoryPalette.vue
<script setup lang="ts">
import { hstack, vstack } from '@doubleaxe/daxfb-calculator-styles/patterns';
</script>

<template>
    <div :class="vstack({})">
        <div :class="hstack({ flex: 'none', alignSelf: 'center' })">
            <slot name="filterPanel" />
        </div>
        <div :class="hstack({ flexGrow: 1, alignSelf: 'start' })">
            <slot name="itemList" />
        </div>
    </div>
</template>

// packages/calculator-core/src/ui/factory-palette/FactoryPalette.tsx
import { hstack, vstack } from '@doubleaxe/daxfb-calculator-styles/patterns';

import type { BaseProps } from '#core/types/props.js';
import { assignDisplayName, extractComponentsForCompoundParent } from '#core/utils/tsxhelpers.js';

function FilterPanel({ children }: BaseProps) {
    return children;
}
assignDisplayName(FilterPanel, 'FilterPanel');
function ItemList({ children }: BaseProps) {
    return children;
}
assignDisplayName(ItemList, 'ItemList');

function FactoryPalette({ children }: BaseProps) {
    const [filterPanel, itemList] = extractComponentsForCompoundParent(children, ['FilterPanel', 'ItemList']);

    return (
        <div className={vstack({})}>
            <div
                className={hstack({
                    flex: 'none',
                    alignSelf: 'center',
                })}
            >
                {filterPanel}
            </div>
            <div
                className={hstack({
                    flexGrow: 1,
                    alignSelf: 'start',
                })}
            >
                {itemList}
            </div>
        </div>
    );
}

FactoryPalette.FilterPanel = FilterPanel;
FactoryPalette.ItemList = ItemList;

export default FactoryPalette;
