// packages/calculator-ui/src/App.tsx
import { css } from '@doubleaxe/daxfb-calculator-styles/css';
import { Center, Loader } from '@mantine/core';
import { lazy, Suspense, useEffect, useState } from 'react';

import MantineInit from '#core/ui/MantineInit';

import { GameIds } from './GameIds';

const LandingPage = lazy(() => import(`./pages/LandingPage`));
const CoiGamePage = lazy(() => import('./pages/CoiGamePage'));

function getGameId() {
    const params = new URLSearchParams(window.location.search);
    return params.get('gameId');
}

export default function App() {
    const [gameId, setGameId] = useState<null | string>(getGameId());

    useEffect(() => {
        const updateGameId = () => {
            setGameId(getGameId());
        };

        window.addEventListener('popstate', updateGameId);
        return () => {
            window.removeEventListener('popstate', updateGameId);
        };
    }, []);

    let PageComponent = LandingPage;
    switch (gameId) {
        case GameIds.COI:
            PageComponent = CoiGamePage;
            break;
    }

    return (
        <MantineInit>
            <Suspense
                fallback={
                    <Center className={css({ width: '100%', height: '100%' })}>
                        <Loader />
                    </Center>
                }
            >
                <PageComponent />
            </Suspense>
        </MantineInit>
    );
}

// packages/calculator-ui/src/App.vue
<script setup lang="ts">
import MantineInit from '@doubleaxe/daxfb-calculator-core/ui/MantineInit';
import { css } from '@doubleaxe/daxfb-calculator-styles/css';
import ProgressSpinner from 'primevue/progressspinner';
import { computed, defineAsyncComponent, onMounted, onUnmounted, ref } from 'vue';

import { GameIds } from './GameIds.js';

const LandingPage = defineAsyncComponent(() => import('./pages/LandingPage.vue'));
const CoiGamePage = defineAsyncComponent(() => import('./pages/CoiGamePage.vue'));

const getGameId = () => new URLSearchParams(window.location.search).get('gameId');

const gameId = ref<null | string>(getGameId());

const updateGameId = () => {
    gameId.value = getGameId();
};

onMounted(() => {
    window.addEventListener('popstate', updateGameId);
});

onUnmounted(() => {
    window.removeEventListener('popstate', updateGameId);
});

const pageComponent = computed(() => (gameId.value === GameIds.COI ? CoiGamePage : LandingPage));

const fallbackClass = css({
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
});
</script>

<template>
    <MantineInit>
        <Suspense>
            <component :is="pageComponent" />
            <template #fallback>
                <div :class="fallbackClass">
                    <ProgressSpinner />
                </div>
            </template>
        </Suspense>
    </MantineInit>
</template>
