// packages/calculator-ui/src/pages/LandingPage.tsx
import { Anchor, AppShell, Container, List, Paper, Text, Title } from '@mantine/core';

import { GameIds } from '../GameIds';

export default function LandingPage() {
    return (
        <AppShell footer={{ height: 60 }} p='md'>
            <AppShell.Main>
                <Container mt='xl' size='sm'>
                    <Paper p='xl' shadow='xs'>
                        <Title mb='lg' order={1} ta='center'>
                            Select Game
                        </Title>
                        <List size='md' spacing='md' withPadding>
                            <List.Item>
                                <Anchor href={`?gameId=${GameIds.COI}`} size='lg'>
                                    Captain of Industry
                                </Anchor>
                            </List.Item>
                        </List>
                    </Paper>
                </Container>
            </AppShell.Main>
            <AppShell.Footer>
                <Text size='sm' ta='center'>
                    Extra small text
                </Text>
            </AppShell.Footer>
        </AppShell>
    );
}

// packages/calculator-ui/src/pages/LandingPage.vue
<script setup lang="ts">
import { css } from '@doubleaxe/daxfb-calculator-styles/css';

import { GameIds } from '../GameIds.js';

const shell = css({ display: 'flex', flexDirection: 'column', width: '100%', height: '100%' });
const main = css({ flex: 1, padding: '4' });
const container = css({ maxWidth: '2xl', marginInline: 'auto', marginTop: '8' });
const paper = css({
    padding: '8',
    boxShadow: 'xs',
    borderRadius: 'lg',
    backgroundColor: 'var(--p-content-background)',
});
const title = css({ marginBottom: '5', textAlign: 'center', fontSize: '3xl', fontWeight: 'bold' });
const list = css({ fontSize: 'md', paddingLeft: '6' });
const listItem = css({ marginBottom: '4' });
const anchor = css({ fontSize: 'lg', color: 'var(--p-primary-color)' });
const footer = css({ height: '60px', display: 'flex', alignItems: 'center', justifyContent: 'center' });
const footerText = css({ fontSize: 'sm', textAlign: 'center' });
</script>

<template>
    <div :class="shell">
        <div :class="main">
            <div :class="container">
                <div :class="paper">
                    <h1 :class="title">Select Game</h1>
                    <ul :class="list">
                        <li :class="listItem">
                            <a :class="anchor" :href="`?gameId=${GameIds.COI}`">Captain of Industry</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <footer :class="footer">
            <span :class="footerText">Extra small text</span>
        </footer>
    </div>
</template>
